---
- hosts: all
  become_user: root
  become: true

  #vars_files:
    #- vars/default.yml

  tasks:
    - name: Update APT package manager repositories cache
      apt: 
        update_cache: yes
      become: true
    
    - name: Install OpenJDK Java
      apt: name=openjdk-8-jdk state=present
      become: true

    - name: Install Maven
      apt: name=maven state=present
      become: true

    - name: copy war file
      copy: src=./target/api-gateway.jar dest=/home/ubuntu
